### ISSUE TITLE
Failing deployment action

### ISSUE THREAD

**Issue by Blukzen** [Blukzen/fairandsquarebs#18]
Error: Request body larger than maxBodyLength limit
    at RedirectableRequest.module.exports.549.RedirectableRequest.write (/home/runner/work/_actions/TryGhost/action-deploy-theme/v1.0.0/dist/index.js:7813:24)
    at FormData.ondata (internal/streams/legacy.js:17:31)
    at FormData.emit (events.js:210:5)
    at FormData.module.exports.547.CombinedStream.write (/home/runner/work/_actions/TryGhost/action-deploy-theme/v1.0.0/dist/index.js:7639:8)
    at DelayedStream.ondata (internal/streams/legacy.js:17:31)
    at DelayedStream.emit (events.js:210:5)
    at DelayedStream.module.exports.152.DelayedStream._handleEmit (/home/runner/work/_actions/TryGhost/action-deploy-theme/v1.0.0/dist/index.js:2378:15)
    at ReadStream.source.emit (/home/runner/work/_actions/TryGhost/action-deploy-theme/v1.0.0/dist/index.js:2325:19)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11) {
  isAxiosError: true,
  toJSON: [Function]

**Comment by Blukzen** [comment]
https://forum.ghost.org/t/deploy-ghost-theme-github-actions-ci-error-request-body-larger-than-maxbodylength-limit/11222
